"""empty message

Revision ID: 04c6eff521e2
Revises: 039bd30ccef4
Create Date: 2020-05-19 11:34:07.281157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c6eff521e2'
down_revision = '039bd30ccef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sizes', sa.String(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('selected_size', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'])
    op.drop_column('task', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('size', sa.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'selected_size')
    op.drop_column('task', 'product_id')
    op.drop_table('product')
    # ### end Alembic commands ###
