"""empty message

Revision ID: 188151855d14
Revises: 6f3f038a81f4
Create Date: 2020-05-20 01:11:05.545646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188151855d14'
down_revision = '6f3f038a81f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'profile', 'user', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'task', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'])
    op.drop_column('task', 'size')
    op.add_column('user', sa.Column('proxies', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'proxies')
    op.add_column('task', sa.Column('size', sa.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'profile', type_='foreignkey')
    # ### end Alembic commands ###
