"""empty message

Revision ID: 1a311b7a02f7
Revises: 188151855d14
Create Date: 2020-06-02 23:08:11.292688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a311b7a02f7'
down_revision = '188151855d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'email')
    # ### end Alembic commands ###
