"""empty message

Revision ID: 59564f63b0ae
Revises: c2889ee965a5
Create Date: 2020-06-10 23:03:10.493772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59564f63b0ae'
down_revision = 'c2889ee965a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'profile', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'profile_id')
    # ### end Alembic commands ###
