"""empty message

Revision ID: 7d1e9feceecb
Revises: ce38b570a62b
Create Date: 2020-05-19 14:11:08.461302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1e9feceecb'
down_revision = 'ce38b570a62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profile', 'user', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'task', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'])
    op.drop_column('task', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('size', sa.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'owner_id')
    # ### end Alembic commands ###
