"""empty message

Revision ID: a427de7c4a9c
Revises: 4730a6f6b561
Create Date: 2020-05-19 11:00:00.049447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a427de7c4a9c'
down_revision = '4730a6f6b561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'created_by_id')
    # ### end Alembic commands ###
