"""empty message

Revision ID: ab17a75e51ca
Revises: 59564f63b0ae
Create Date: 2020-06-12 15:41:49.546735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab17a75e51ca'
down_revision = '59564f63b0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('proxy', sa.String(), nullable=True))
    op.create_foreign_key(None, 'task', 'profile', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'proxy')
    # ### end Alembic commands ###
