"""empty message

Revision ID: c2889ee965a5
Revises: 1a311b7a02f7
Create Date: 2020-06-10 20:05:15.588918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2889ee965a5'
down_revision = '1a311b7a02f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('credit_card', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'credit_card')
    # ### end Alembic commands ###
