"""empty message

Revision ID: ce38b570a62b
Revises: f998098d683a
Create Date: 2020-05-19 11:55:53.731766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce38b570a62b'
down_revision = 'f998098d683a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=15), nullable=True),
    sa.Column('province', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'task', 'product', ['product_id'], ['id'])
    op.drop_column('task', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('size', sa.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_table('profile')
    # ### end Alembic commands ###
