"""empty message

Revision ID: d960b75824ca
Revises: ba7a57383e3e
Create Date: 2020-05-15 15:28:06.876531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd960b75824ca'
down_revision = 'ba7a57383e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_first_name', table_name='users')
    op.drop_index('ix_users_last_name', table_name='users')
    op.create_unique_constraint(None, 'users', ['key'])
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_last_name', 'users', ['last_name'], unique=False)
    op.create_index('ix_users_first_name', 'users', ['first_name'], unique=False)
    # ### end Alembic commands ###
