name: telegram alerts
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
          The ${{ github.event_name }} event triggered second step.
          show the github varable ref: ${{ github.ref }}
          show the github varable commit: ${{ github.sha }}
          show the github varable ref: {{ commit.ref }}
          show the github varable commit: {{ commit.sha }}
